#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Apply reviewed copy back into the site and the READMEs.

copy/site_strings.json -> site/strings.js (generated; the page imports it) and the
<title> / meta description / Open Graph / Twitter tags in site/index.html.
copy/readme_sections.md -> README.md and README.zh.md (with --readme).

Keys are stable: only `en` and `zh` are read from the JSON. A key missing from the
JSON keeps its previous value and is reported; an unknown key is reported and
ignored; a value longer than `max_length` is reported (and still applied).

  .venv\\Scripts\\python scripts/import_copy.py            # strings + meta
  .venv\\Scripts\\python scripts/import_copy.py --readme   # also rebuild the READMEs
  .venv\\Scripts\\python scripts/import_copy.py --check    # report only, write nothing
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COPY_JSON = ROOT / "copy" / "site_strings.json"
COPY_README = ROOT / "copy" / "readme_sections.md"
STRINGS_JS = ROOT / "site" / "strings.js"
INDEX_HTML = ROOT / "site" / "index.html"
SITE_CONFIG = ROOT / "site" / "config.json"
LANGS = ("en", "zh")

# meta.* keys are written into index.html; everything else into strings.js.
META_TARGETS = {
    "meta.title": [("title", None)],
    "meta.description": [("meta", "name=\"description\"")],
    "meta.ogTitle": [("meta", "property=\"og:title\""), ("meta", "name=\"twitter:title\"")],
    "meta.ogDescription": [("meta", "property=\"og:description\"")],
    "meta.twitterDescription": [("meta", "name=\"twitter:description\"")],
    "meta.ogImageAlt": [("meta", "property=\"og:image:alt\"")],
}


def load_copy(path: Path = COPY_JSON) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    entries = data["strings"] if isinstance(data, dict) else data
    for entry in entries:
        for field in ("key", "en", "zh"):
            if field not in entry:
                raise ValueError(f"entry without {field!r}: {entry}")
    return entries


def current_strings() -> dict:
    """Read the STRINGS object the site currently ships (via node)."""
    if not STRINGS_JS.exists():
        return {lang: {} for lang in LANGS}
    script = "import('./site/strings.js').then(m => process.stdout.write(JSON.stringify(m.STRINGS)))"
    result = subprocess.run(["node", "-e", script], cwd=ROOT, capture_output=True, text=True, encoding="utf-8", check=True)
    return json.loads(result.stdout)


def flatten(obj: dict, prefix: str = "") -> dict[str, str]:
    flat: dict[str, str] = {}
    for key, value in obj.items():
        name = f"{prefix}{key}"
        if isinstance(value, dict):
            flat.update(flatten(value, f"{name}."))
        elif isinstance(value, list):
            for index, item in enumerate(value):
                flat[f"{name}.{index}"] = item
        else:
            flat[name] = value
    return flat


def unflatten(flat: dict[str, str]) -> dict:
    nested: dict = {}
    for key, value in flat.items():
        parts = key.split(".")
        node = nested
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = value
    # dicts whose keys are all consecutive integers become arrays
    def arrays(node):
        if isinstance(node, dict):
            if node and all(k.isdigit() for k in node):
                return [arrays(node[k]) for k in sorted(node, key=int)]
            return {k: arrays(v) for k, v in node.items()}
        return node
    return arrays(nested)


def render_strings_js(strings: dict) -> str:
    body = json.dumps(strings, ensure_ascii=False, indent=2)
    return (
        "// GENERATED by scripts/import_copy.py from copy/site_strings.json — do not edit by hand.\n"
        "// Edit copy/site_strings.json (en / zh only) and run the import script.\n"
        f"export const STRINGS = {body};\n"
    )


def patch_index_html(html: str, meta: dict[str, str]) -> str:
    for key, value in meta.items():
        for kind, selector in META_TARGETS.get(key, []):
            if kind == "title":
                html, n = re.subn(r"<title>[^<]*</title>", f"<title>{escape(value)}</title>", html, count=1)
            else:
                pattern = re.compile(r'(<meta\s+' + re.escape(selector) + r'\s+content=")[^"]*(")')
                html, n = pattern.subn(lambda m: f'{m.group(1)}{escape(value)}{m.group(2)}', html, count=1)
            if n == 0:
                print(f"warning: no {kind} tag for {key} ({selector}) in index.html")
    return html


def escape(value: str) -> str:
    return value.replace("&", "&amp;").replace('"', "&quot;").replace("<", "&lt;").replace(">", "&gt;")


def site_url() -> str:
    """Canonical public URL from site/config.json (trailing slash guaranteed)."""
    url = json.loads(SITE_CONFIG.read_text(encoding="utf-8"))["site_url"]
    return url if url.endswith("/") else url + "/"


def patch_site_url(html: str, url: str) -> str:
    """Point the canonical link, og:url, og:image and twitter:image at the site URL."""
    targets = [
        (r'(<link\s+rel="canonical"\s+href=")[^"]*(")', url),
        (r'(<meta\s+property="og:url"\s+content=")[^"]*(")', url),
        (r'(<meta\s+property="og:image"\s+content=")[^"]*(")', url + "og-image.png"),
        (r'(<meta\s+name="twitter:image"\s+content=")[^"]*(")', url + "og-image.png"),
    ]
    for pattern, value in targets:
        html, n = re.subn(pattern, lambda m, v=value: f"{m.group(1)}{escape(v)}{m.group(2)}", html, count=1)
        if n == 0:
            print(f"warning: no tag for {pattern} in index.html")
    return html


def apply_strings(entries: list[dict], check: bool, allow_new: bool = False) -> int:
    shipped = {lang: flatten(current_strings().get(lang, {})) for lang in LANGS}
    known_keys = set(shipped["en"]) | set(shipped["zh"])
    problems = 0
    incoming = {entry["key"]: entry for entry in entries}
    for key in sorted(known_keys - set(incoming)):
        if key.startswith("meta."):
            continue
        print(f"warning: key removed from copy, keeping previous value: {key}")
        problems += 1
    new_strings = {lang: dict(shipped[lang]) for lang in LANGS}
    meta: dict[str, str] = {}
    for key, entry in incoming.items():
        if key.startswith("meta."):
            meta[key] = entry["en"] if entry["en"] == entry["zh"] else f"{entry['en']} {entry['zh']}".strip()
            for lang in LANGS:
                limit = entry.get("max_length")
                if limit and len(entry[lang]) > limit:
                    print(f"warning: {key}.{lang} is {len(entry[lang])} chars, max_length {limit}")
                    problems += 1
            continue
        if known_keys and key not in known_keys:
            if allow_new and entry.get("context"):
                print(f"note: new key added: {key}")
            else:
                print(f"warning: unknown key ignored: {key} (pass --allow-new to add keys that carry a context)")
                problems += 1
                continue
        for lang in LANGS:
            value = entry[lang]
            limit = entry.get("max_length")
            if limit and len(value) > limit:
                print(f"warning: {key}.{lang} is {len(value)} chars, max_length {limit}")
                problems += 1
            new_strings[lang][key] = value
    if check:
        print(f"check only: {len(incoming)} entries, {problems} warnings")
        return problems
    nested = {lang: unflatten(new_strings[lang]) for lang in LANGS}
    STRINGS_JS.write_text(render_strings_js(nested), encoding="utf-8")
    html = INDEX_HTML.read_text(encoding="utf-8")
    INDEX_HTML.write_text(patch_site_url(patch_index_html(html, meta), site_url()), encoding="utf-8")
    print(f"wrote {STRINGS_JS} ({sum(len(v) for v in new_strings.values())} strings) and meta tags in {INDEX_HTML}; {problems} warnings")
    return problems


SECTION_RE = re.compile(r"^<!-- section: (\d+) \| file: (README\.md|README\.zh\.md) \| context: .*? -->$", re.M)


def check_readme_url(text: str, name: str) -> None:
    """The READMEs' "Try it" line must point at the canonical site URL."""
    urls = set(re.findall(r"https?://[^\s)]+", text))
    stale = [u for u in urls if u.rstrip("/").endswith("github.io/ask-the-fly") or u.startswith("https://askthefly.app") and u.rstrip("/") + "/" != site_url()]
    if stale:
        print(f"warning: {name} links to {', '.join(sorted(stale))} instead of {site_url()}")


def apply_readme(path: Path = COPY_README) -> None:
    text = path.read_text(encoding="utf-8")
    matches = list(SECTION_RE.finditer(text))
    if not matches:
        raise ValueError(f"{path}: no section markers found")
    files: dict[str, list[str]] = {}
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        body = text[match.end():end].strip("\n")
        files.setdefault(match.group(2), []).append(body)
    for name, sections in files.items():
        target = ROOT / name
        target.write_text("\n\n".join(sections).rstrip("\n") + "\n", encoding="utf-8")
        print(f"wrote {target} ({len(sections)} sections)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--readme", action="store_true", help="also rebuild README.md / README.zh.md from copy/readme_sections.md")
    parser.add_argument("--check", action="store_true", help="report warnings without writing")
    parser.add_argument("--allow-new", action="store_true", help="accept keys not yet in site/strings.js (they must carry a context)")
    args = parser.parse_args()
    problems = apply_strings(load_copy(), args.check, args.allow_new)
    if args.readme and not args.check:
        apply_readme()
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
